# Generated by Django 4.1.7 on 2023-04-08 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_id', models.AutoField(db_column='document_id', primary_key=True, serialize=False)),
                ('create_time', models.CharField(max_length=50)),
                ('update_time', models.CharField(max_length=50)),
                ('status', models.IntegerField(choices=[(0, '未审核'), (1, '已审核'), (2, '审核不通过')])),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('reason', models.CharField(default='', max_length=100)),
            ],
            options={
                'db_table': 'document',
            },
        ),
        migrations.CreateModel(
            name='DocumentField',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('field_name', models.CharField(db_column='field_name', max_length=50)),
            ],
            options={
                'db_table': 'document_field',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('permission_id', models.AutoField(db_column='permission_id', primary_key=True, serialize=False)),
                ('permission_name', models.CharField(db_column='permission_name', max_length=50)),
            ],
            options={
                'db_table': 'permission',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=50)),
                ('isOpened', models.BooleanField(db_column='isOpened', default=False)),
            ],
            options={
                'db_table': 'settings',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(db_column='user_id', primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('role', models.IntegerField(choices=[(0, '普通用户'), (1, '管理员')])),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_allowed', models.BooleanField(db_column='is_allowed', default=True)),
                ('permission', models.ForeignKey(db_column='permission_id', on_delete=django.db.models.deletion.CASCADE, to='app.permission')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
            options={
                'db_table': 'user_permission',
                'unique_together': {('user_id', 'permission_id')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='permission',
            field=models.ManyToManyField(through='app.UserPermission', to='app.permission'),
        ),
        migrations.CreateModel(
            name='QApair',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('document_id', models.ForeignKey(db_column='document_id', on_delete=django.db.models.deletion.CASCADE, to='app.document')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
            options={
                'db_table': 'q_a_document',
            },
        ),
        migrations.AddField(
            model_name='document',
            name='auditor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auditor', to='app.user'),
        ),
        migrations.AddField(
            model_name='document',
            name='field',
            field=models.ForeignKey(db_column='field_id', on_delete=django.db.models.deletion.CASCADE, to='app.documentfield'),
        ),
        migrations.AddField(
            model_name='document',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='user', to='app.user'),
        ),
    ]
