# Generated by Django 4.1.7 on 2023-03-25 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.IntegerField(choices=[(0, '未审核'), (1, '已审核'), (2, '审核不通过')]),
        ),
    ]
