# Generated by Django 4.1.7 on 2023-03-25 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_document_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='reason',
            field=models.CharField(default='', max_length=100),
        ),
    ]
