# Generated by Django 4.1.7 on 2023-03-25 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_document_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='auditor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auditor', to='app.user'),
        ),
        migrations.AlterField(
            model_name='document',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='user', to='app.user'),
        ),
    ]
